// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/connection/connections-response.proto

package connectionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindConnectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   []*FoundConnection     `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	LeftRange     []*ConnectionsRange    `protobuf:"bytes,2,rep,name=left_range,json=leftRange,proto3" json:"left_range,omitempty"`
	RightRange    []*ConnectionsRange    `protobuf:"bytes,3,rep,name=right_range,json=rightRange,proto3" json:"right_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindConnectionsResponse) Reset() {
	*x = FindConnectionsResponse{}
	mi := &file_proto_connection_connections_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindConnectionsResponse) ProtoMessage() {}

func (x *FindConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_connections_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindConnectionsResponse.ProtoReflect.Descriptor instead.
func (*FindConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_connection_connections_response_proto_rawDescGZIP(), []int{0}
}

func (x *FindConnectionsResponse) GetConnections() []*FoundConnection {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *FindConnectionsResponse) GetLeftRange() []*ConnectionsRange {
	if x != nil {
		return x.LeftRange
	}
	return nil
}

func (x *FindConnectionsResponse) GetRightRange() []*ConnectionsRange {
	if x != nil {
		return x.RightRange
	}
	return nil
}

type FoundConnection struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price              int32                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Line               int32                  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	DepartureCountry   string                 `protobuf:"bytes,4,opt,name=departure_country,json=departureCountry,proto3" json:"departure_country,omitempty"`
	DestinationCountry string                 `protobuf:"bytes,5,opt,name=destination_country,json=destinationCountry,proto3" json:"destination_country,omitempty"`
	DepartureTime      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`
	ArrivalTime        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=arrival_time,json=arrivalTime,proto3" json:"arrival_time,omitempty"`
	EstimatedDuration  int32                  `protobuf:"varint,8,opt,name=estimated_duration,json=estimatedDuration,proto3" json:"estimated_duration,omitempty"`
	SellBefore         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=sell_before,json=sellBefore,proto3" json:"sell_before,omitempty"`
	TicketsLeft        int32                  `protobuf:"varint,10,opt,name=tickets_left,json=ticketsLeft,proto3" json:"tickets_left,omitempty"`
	Fits               bool                   `protobuf:"varint,11,opt,name=fits,proto3" json:"fits,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FoundConnection) Reset() {
	*x = FoundConnection{}
	mi := &file_proto_connection_connections_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoundConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoundConnection) ProtoMessage() {}

func (x *FoundConnection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_connections_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoundConnection.ProtoReflect.Descriptor instead.
func (*FoundConnection) Descriptor() ([]byte, []int) {
	return file_proto_connection_connections_response_proto_rawDescGZIP(), []int{1}
}

func (x *FoundConnection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FoundConnection) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *FoundConnection) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *FoundConnection) GetDepartureCountry() string {
	if x != nil {
		return x.DepartureCountry
	}
	return ""
}

func (x *FoundConnection) GetDestinationCountry() string {
	if x != nil {
		return x.DestinationCountry
	}
	return ""
}

func (x *FoundConnection) GetDepartureTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureTime
	}
	return nil
}

func (x *FoundConnection) GetArrivalTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ArrivalTime
	}
	return nil
}

func (x *FoundConnection) GetEstimatedDuration() int32 {
	if x != nil {
		return x.EstimatedDuration
	}
	return 0
}

func (x *FoundConnection) GetSellBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.SellBefore
	}
	return nil
}

func (x *FoundConnection) GetTicketsLeft() int32 {
	if x != nil {
		return x.TicketsLeft
	}
	return 0
}

func (x *FoundConnection) GetFits() bool {
	if x != nil {
		return x.Fits
	}
	return false
}

type ConnectionsRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Number        int32                  `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	MinPrice      int32                  `protobuf:"varint,4,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionsRange) Reset() {
	*x = ConnectionsRange{}
	mi := &file_proto_connection_connections_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionsRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionsRange) ProtoMessage() {}

func (x *ConnectionsRange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_connections_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionsRange.ProtoReflect.Descriptor instead.
func (*ConnectionsRange) Descriptor() ([]byte, []int) {
	return file_proto_connection_connections_response_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectionsRange) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *ConnectionsRange) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *ConnectionsRange) GetMinPrice() int32 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

var File_proto_connection_connections_response_proto protoreflect.FileDescriptor

const file_proto_connection_connections_response_proto_rawDesc = "" +
	"\n" +
	"+proto/connection/connections-response.proto\x12\n" +
	"connection\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x01\n" +
	"\x17FindConnectionsResponse\x12=\n" +
	"\vconnections\x18\x01 \x03(\v2\x1b.connection.FoundConnectionR\vconnections\x12;\n" +
	"\n" +
	"left_range\x18\x02 \x03(\v2\x1c.connection.ConnectionsRangeR\tleftRange\x12=\n" +
	"\vright_range\x18\x03 \x03(\v2\x1c.connection.ConnectionsRangeR\n" +
	"rightRange\"\xce\x03\n" +
	"\x0fFoundConnection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x05R\x05price\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12+\n" +
	"\x11departure_country\x18\x04 \x01(\tR\x10departureCountry\x12/\n" +
	"\x13destination_country\x18\x05 \x01(\tR\x12destinationCountry\x12A\n" +
	"\x0edeparture_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rdepartureTime\x12=\n" +
	"\farrival_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\varrivalTime\x12-\n" +
	"\x12estimated_duration\x18\b \x01(\x05R\x11estimatedDuration\x12;\n" +
	"\vsell_before\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"sellBefore\x12!\n" +
	"\ftickets_left\x18\n" +
	" \x01(\x05R\vticketsLeft\x12\x12\n" +
	"\x04fits\x18\v \x01(\bR\x04fits\"w\n" +
	"\x10ConnectionsRange\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x16\n" +
	"\x06number\x18\x03 \x01(\x05R\x06number\x12\x1b\n" +
	"\tmin_price\x18\x04 \x01(\x05R\bminPriceB%Z#yourmodule/internal/pb/connectionpbb\x06proto3"

var (
	file_proto_connection_connections_response_proto_rawDescOnce sync.Once
	file_proto_connection_connections_response_proto_rawDescData []byte
)

func file_proto_connection_connections_response_proto_rawDescGZIP() []byte {
	file_proto_connection_connections_response_proto_rawDescOnce.Do(func() {
		file_proto_connection_connections_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_connection_connections_response_proto_rawDesc), len(file_proto_connection_connections_response_proto_rawDesc)))
	})
	return file_proto_connection_connections_response_proto_rawDescData
}

var file_proto_connection_connections_response_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_connection_connections_response_proto_goTypes = []any{
	(*FindConnectionsResponse)(nil), // 0: connection.FindConnectionsResponse
	(*FoundConnection)(nil),         // 1: connection.FoundConnection
	(*ConnectionsRange)(nil),        // 2: connection.ConnectionsRange
	(*timestamppb.Timestamp)(nil),   // 3: google.protobuf.Timestamp
}
var file_proto_connection_connections_response_proto_depIdxs = []int32{
	1, // 0: connection.FindConnectionsResponse.connections:type_name -> connection.FoundConnection
	2, // 1: connection.FindConnectionsResponse.left_range:type_name -> connection.ConnectionsRange
	2, // 2: connection.FindConnectionsResponse.right_range:type_name -> connection.ConnectionsRange
	3, // 3: connection.FoundConnection.departure_time:type_name -> google.protobuf.Timestamp
	3, // 4: connection.FoundConnection.arrival_time:type_name -> google.protobuf.Timestamp
	3, // 5: connection.FoundConnection.sell_before:type_name -> google.protobuf.Timestamp
	3, // 6: connection.ConnectionsRange.date:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_connection_connections_response_proto_init() }
func file_proto_connection_connections_response_proto_init() {
	if File_proto_connection_connections_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_connection_connections_response_proto_rawDesc), len(file_proto_connection_connections_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_connection_connections_response_proto_goTypes,
		DependencyIndexes: file_proto_connection_connections_response_proto_depIdxs,
		MessageInfos:      file_proto_connection_connections_response_proto_msgTypes,
	}.Build()
	File_proto_connection_connections_response_proto = out.File
	file_proto_connection_connections_response_proto_goTypes = nil
	file_proto_connection_connections_response_proto_depIdxs = nil
}
